[package]
name = "vizuara-scene"
version = "0.1.0"
edition = "2021"
description = "Scene management for Vizuara"
authors = ["Vizuara Contributors"]
license = "MIT OR Apache-2.0"

[dependencies]
vizuara-core = { path = "../vizuara-core" }
