[package]
name = "vizuara-plots"
version = "0.1.0"
edition = "2021"
description = "Vizuara module: vizuara-plots"
authors = ["Vizuara Contributors"]
license = "MIT OR Apache-2.0"

[dependencies]
vizuara-core = { path = "../vizuara-core" }
