[package]
name = "vizuara-components"
version = "0.1.0"
edition = "2021"
description = "Vizuara module: vizuara-components"
authors = ["Vizuara Contributors"]
license = "MIT OR Apache-2.0"

[dependencies]
vizuara-core = { path = "../vizuara-core" }
nalgebra = { workspace = true }
